print("Reglas del Monopoly")
print("1. Preparación:")
print("   a. Coloca el tablero de juego sobre una superficie plana.")
print("   b. Cada jugador elige una ficha y la coloca en la casilla de Salida.")
print("   c. Se elige a un jugador para que sea el banquero.")
print("   d. El banquero reparte a cada jugador una cantidad inicial de dinero.")
print("   e. Coloca las tarjetas de Propiedad, las cartas de Suerte y de Caja de Comunidad en sus lugares correspondientes.")
print("2. Desarrollo del juego:")
print("   a. Los jugadores lanzan los dados y mueven sus fichas según el resultado.")
print("   b. Si caes en una propiedad sin dueño, puedes comprarla del banco.")
print("   c. Si caes en una propiedad con dueño, debes pagar la renta al propietario.")
print("   d. Si no deseas comprar una propiedad, el banco la subasta.")
print("   e. Si caes en una casilla de Suerte o Caja de Comunidad, toma la carta superior y sigue las instrucciones.")
print("   f. Si caes en una casilla de Impuesto, paga el monto correspondiente al banco.")
print("   g. Si caes en la casilla de 'Ve a la Cárcel', debes ir directamente a la cárcel sin pasar por la Salida.")
print("3. Construcción de casas y hoteles:")
print("   a. Una vez que poseas todas las propiedades de un color, puedes comenzar a construir casas y hoteles.")
print("   b. Debes construir uniformemente; no puedes construir un segundo hotel en una propiedad hasta que todas las propiedades del grupo tengan al menos un hotel.")
print("   c. Paga al banco el precio de las casas y hoteles según el valor indicado en la tarjeta de propiedad.")
print("4. Hipotecas:")
print("   a. Si necesitas dinero, puedes hipotecar tus propiedades al banco.")
print("   b. Para hipotecar una propiedad, recibe el valor de hipoteca indicado en la tarjeta de propiedad.")
print("   c. Para deshipotecar, paga el valor de la hipoteca más un 10% de interés.")
print("5. Bancarrota:")
print("   a. Si debes más dinero del que puedes pagar, debes declararte en bancarrota.")
print("   b. Si te declaras en bancarrota a otro jugador, entrega todas tus propiedades y dinero restante a ese jugador.")
print("   c. Si te declaras en bancarrota al banco, todas tus propiedades son subastadas.")
print("6. Final del juego:")
print("   a. El juego termina cuando solo queda un jugador con dinero, o cuando todos los jugadores menos uno se declaran en bancarrota.")
print("   b. El jugador restante es declarado ganador.")