print("Persona 1: ¡Hola! ¿Cómo estás?")
print("Persona 2: Hola, estoy bien, gracias. ¿Y tú?")
print("Persona 1: Estoy bastante bien también. ¿Has visto cómo está el clima hoy?")
print("Persona 2: Sí, parece que va a llover más tarde.")
print("Persona 1: ¿Y qué opinas sobre la comida del nuevo restaurante en la esquina?")
print("Persona 2: La probé la semana pasada y estaba deliciosa.")
print("Persona 1: Genial, tengo que ir a probarla entonces. ¿Y qué hay de tu trabajo?")
print("Persona 2: El trabajo va bien, gracias por preguntar. ¿Y tú?")
print("Persona 1: Todo bien por mi parte también. Bueno, me tengo que ir. ¡Hasta luego!")
print("Persona 2: ¡Hasta luego!")